"""
Django settings for pawtohome project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

#take enviornment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY") 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #DEPENDENCIES
    'storages',

    #APPS ,
    'loginservice',

    #Django-Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'reportsservice',
    'Mapservice',
    'ProfileService',
    'Homeinfo',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #Django-Allauth middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'pawtohome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Templates globales
        ],
        'APP_DIRS': True,  # Permite templates por app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pawtohome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración flexible: PostgreSQL si hay configuración, SQLite si no
if os.getenv("DB_NAME"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME"),
            'USER': os.getenv("DB_USER"),
            'PASSWORD': os.getenv("DB_PASSWORD"),
            'HOST': os.getenv("DB_HOST"),
            'PORT': os.getenv("DB_PORT"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Para producción (collectstatic)

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Carpeta de archivos estáticos durante desarrollo
]

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'loginservice.CustomUser'

#Django-Allauth Config
AUTHENTICATION_BACKENDS = [
    #Default backends
    'django.contrib.auth.backends.ModelBackend',

    # For Google 
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = int(os.getenv("SITE_ID"))

# Provider specific settings

#Basic Config.
LOGIN_URL = 'loginservice:login-register'
LOGIN_REDIRECT_URL = 'Homeinfo:home'
LOGOUT_REDIRECT_URL = 'Homeinfo:home'

# ========== CLOUDFLARE R2 STORAGE CONFIGURATION ==========

# Configuración de Cloudflare R2
USE_CLOUDFLARE_R2 = os.getenv('USE_CLOUDFLARE_R2', 'False').lower() == 'true'

if USE_CLOUDFLARE_R2:
    # Credenciales de Cloudflare R2
    CLOUDFLARE_R2_ACCESS_KEY_ID = os.getenv('CLOUDFLARE_R2_ACCESS_KEY_ID')
    CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.getenv('CLOUDFLARE_R2_SECRET_ACCESS_KEY')
    CLOUDFLARE_R2_BUCKET_NAME = os.getenv('CLOUDFLARE_R2_BUCKET_NAME')
    CLOUDFLARE_R2_ENDPOINT_URL = os.getenv('CLOUDFLARE_R2_ENDPOINT_URL')
    CLOUDFLARE_R2_CUSTOM_DOMAIN = os.getenv('CLOUDFLARE_R2_CUSTOM_DOMAIN', None)
    
    # Configuración de AWS para Cloudflare R2 (compatible con S3)
    AWS_ACCESS_KEY_ID = CLOUDFLARE_R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = CLOUDFLARE_R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = CLOUDFLARE_R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = CLOUDFLARE_R2_ENDPOINT_URL
    AWS_S3_REGION_NAME = 'auto'  # Cloudflare R2 usa 'auto'
    
    # Configuración de URLs y archivos
    AWS_S3_CUSTOM_DOMAIN = CLOUDFLARE_R2_CUSTOM_DOMAIN
    AWS_DEFAULT_ACL = None  # R2 no requiere ACL explícito
    AWS_QUERYSTRING_AUTH = False  # URLs públicas sin autenticación
    AWS_S3_FILE_OVERWRITE = False  # No sobrescribir archivos existentes
    
    # Configurar storages: Media en R2, Static local
    STORAGES = {
        "default": {
            "BACKEND": "pawtohome.storage_backends.CloudflareR2MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # URLs: Media en R2, Static local
    if CLOUDFLARE_R2_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{CLOUDFLARE_R2_CUSTOM_DOMAIN}/media/"
    else:
        # Usar URLs del endpoint de R2 solo para media
        base_url = CLOUDFLARE_R2_ENDPOINT_URL.rstrip('/')
        bucket_name = CLOUDFLARE_R2_BUCKET_NAME
        MEDIA_URL = f"{base_url}/{bucket_name}/media/"
    
    # Static URLs permanecen locales
    STATIC_URL = '/static/'
    
    print(f"✅ Cloudflare R2 configurado para MEDIA - Bucket: {CLOUDFLARE_R2_BUCKET_NAME}")
    print(f"📁 MEDIA_URL: {MEDIA_URL}")
    print(f"🎨 STATIC_URL: {STATIC_URL} (local)")

else:
    # Configuración de almacenamiento local (desarrollo)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    print("📁 Usando almacenamiento local para desarrollo")


